# Generated by Django 4.2.6 on 2024-06-08 15:04

import django.core.validators
from django.db import migrations, models
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_profileimage_post_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(upload_to='profile_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), network.models.validate_image_size]),
        ),
    ]
